#!/bin/sh /etc/rc.common

START=21
STOP=9
USE_PROCD=1

start_service() {
	local status track
	track=$(uci get ucitrack.@mcu[0].exec 2>/dev/null)
	[ -z "$track" ] && {
		uci add ucitrack mcu
		uci set ucitrack.@mcu[0]=mcu
		uci set ucitrack.@mcu[0].exec="/etc/init.d/e750_mcu reload"
		uci commit ucitrack
		/etc/init.d/ucitrack restart
	}
	echo 1 4 1 7 >/proc/sys/kernel/printk
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command /usr/bin/e750-mcu
	procd_close_instance
}

stop_service() {
	killall -9 e750-mcu
	echo 7 4 1 7 >/proc/sys/kernel/printk
	#rmmod soft_uart
}

reload_service() {
	killall -14 e750-mcu
}

shutdown()
{
	echo {\"system\":\"reboot\"} >/tmp/mcu_message
	killall -17 e750-mcu
	sleep 1
}
